version: 0.2
phases:
  install:
    commands:
      - apk add curl
      - pip install --user yamllint awscli
  build:
    commands:
      - yamllint jenkins.yaml
      - aws s3 cp jenkins.yaml s3://${BUCKET}/${ENVIRONMENT_NAME}/jenkins.yaml
      - curl -X POST -u $JENKINS_API_USER:$JENKINS_API_PASSWORD "${JENKINS_URL}/configuration-as-code/reload"