bucket_name: jcasc.${EnvironmentName}.${AWS::Region}.${AWS::AccountId}

iam_policies:
  logs:
    action:
      - logs:CreateLogStream
      - logs:PutLogEvents
  s3-object:
    action:
      - s3:GetObject
      - s3:PutObject
      - s3:ListBucket
    resource:
      - Fn::Sub: arn:aws:s3:::${Bucket}/*
  s3-bucket:
    action:
      - s3:ListBucket
      - s3:GetBucketLocation
    resource:
      - Fn::Sub: arn:aws:s3:::${Bucket}
  vpc-access:
    action:
      - ec2:CreateNetworkInterface
      - ec2:DescribeDhcpOptions
      - ec2:DescribeNetworkInterfaces
      - ec2:DeleteNetworkInterface
      - ec2:DescribeSubnets
      - ec2:DescribeSecurityGroups
      - ec2:DescribeVpcs