bucket_name: jcasc.${EnvironmentName}.${AWS::Region}.${AWS::AccountId}

buildspec:
  version: 0.2
  phases:
    install:
      install:
        runtime-versions:
          python: 3.7
      commands:
        - pip install --user yamllint
    build:
      commands:
        - yamllint jenkins.yaml
        - aws s3 cp jenkins.yaml s3://${BUCKET}/${ENVIRONMENT_NAME}/jenkins.yaml
        - curl -X POST -u $JENKINS_API_USER:$JENKINS_API_PASSWORD "${JENKINS_URL}/configuration-as-code/reload"

trigger_iam_policies:
  CloudWatchEventPolicy:
    action:
      - codebuild:StartBuild
    resource:
      - Fn::GetAtt: [Build,Arn]

codebuild_iam_policies:
  logs:
    action:
      - logs:CreateLogStream
      - logs:PutLogEvents
  s3-object:
    action:
      - s3:GetObject
      - s3:PutObject
      - s3:ListBucket
    resource:
      - Fn::Sub: arn:aws:s3:::${Bucket}/*
  s3-bucket:
    action:
      - s3:ListBucket
      - s3:GetBucketLocation
    resource:
      - Fn::Sub: arn:aws:s3:::${Bucket}
  git-pull:
    action:
      - codecommit:GitPull
    resource:
      - Fn::GetAtt: Repository.Arn
  vpc-access:
    action:
      - ec2:CreateNetworkInterface
      - ec2:DescribeDhcpOptions
      - ec2:DescribeNetworkInterfaces
      - ec2:DeleteNetworkInterface
      - ec2:DescribeSubnets
      - ec2:DescribeSecurityGroups
      - ec2:DescribeVpcs
      - ec2:CreateNetworkInterfacePermission
  secret-manager:
    action:
      - secretsmanager:GetSecretValue
    resource:
      - Ref: JenkinsSecret